# Generated by Django 3.1.2 on 2021-01-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabbackend', '0002_auto_20210119_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocab',
            name='word',
            field=models.CharField(max_length=45),
        ),
    ]
